export enum Types {
  AUTH_CHECKING_FINISH = "AUTH_CHECKING_FINISH",
  AUTH_LOGIN = "AUTH_LOGIN",
  AUTH_LOGOUT = "AUTH_LOGOUT",
  CLIENT_ACTIVE = "CLIENT_ACTIVE",
  CLIENT_CLEAR_ACTIVE = "CLIENT_CLEAR_ACTIVE",
}
